#!/bin/bash

# چک کردن نصب بودن zip و unzip
if ! command -v zip &> /dev/null || ! command -v unzip &> /dev/null; then
    read -p "zip and unzip are not installed. Do you want to install them? (y/n): " confirm_install
    if [[ "$confirm_install" == "y" ]]; then
        sudo apt install zip unzip -y
    else
        echo "Installation aborted."
        exit 1
    fi
fi

# نمایش حجم کل دیسک و فضای خالی
total_space=$(df / --output=size | tail -n1 | awk '{print $1}')
free_space=$(df / --output=avail | tail -n1 | awk '{print $1}')

# تبدیل به GB
total_space_gb=$((total_space / 1024 / 1024))
free_space_gb=$((free_space / 1024 / 1024))

echo "Total Disk Size: ${total_space_gb}G"
echo "Free Disk Space: ${free_space_gb}G"

# گرفتن حجم پوشه‌ها
opt_marzban_size=$(du -s /opt/marzban | awk '{print $1}')
lib_marzban_size=$(du -s /var/lib/marzban | awk '{print $1}')

# محاسبه اندازه پوشه‌ها به GB
opt_marzban_size_gb=$((opt_marzban_size / 1024 / 1024))
lib_marzban_size_gb=$((lib_marzban_size / 1024 / 1024))

total_marzban_size_gb=$((opt_marzban_size_gb + lib_marzban_size_gb))

echo "Total MARZBAN Files Size: ${total_marzban_size_gb}G"

# بررسی کافی بودن فضای دیسک برای عملیات زیپ
if [[ $free_space_gb -lt $total_marzban_size_gb ]]; then
    echo "There is not enough space for ZIP/UNZIP operations."
    exit 1
else
    echo "There is enough space. Continuing with zip and unzip operations."
fi

# ادامه زیپ و آنزیپ
read -p "Do you want to create a zip file for the displayed directories? (y/n): " confirm_zip
if [[ "$confirm_zip" == "y" ]]; then
    cd /opt
    zip -r marzban.zip marzban/
    echo "Zipped /opt/marzban"
    
    cd /var/lib
    zip -r marzban.zip marzban/
    echo "Zipped /var/lib/marzban"
fi

# آپدیت پنل Marzban
read -p "Do you want to update the Marzban panel? (y/n): " confirm_update
if [[ "$confirm_update" == "y" ]]; then
    cd /
    marzban update
    sleep 40
    echo "Update completed. If you need to restore the zip files, please run the script again."
fi

# مرحله بازگردانی اطلاعات ZIP
echo "UNZIP"
read -p "Do you want to restore your backup files? (y/n): " confirm_unzip
if [[ "$confirm_unzip" == "y" ]]; then
    cd /opt
    unzip marzban.zip
    rm marzban.zip

    cd /var/lib
    unzip marzban.zip
    rm marzban.zip
fi

echo "Thank you for running the script!"
exit 0
